name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov black isort mypy
          pip install -e .

      - name: Check code formatting with Black
        run: black --check .

      - name: Check imports with isort
        run: isort --check-only --diff .

      - name: Type checking with mypy
        run: mypy src tests

      - name: Run tests with pytest
        run: pytest tests/ --cov=src --cov-report=term-missing

  block-merge:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Block merge if tests fail
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Tests must pass before merging to main"
            exit 1
          fi
